# global settings
title: "Ondrej Vanka"
author:
  name: Ondrej Vanka
  email: ondrej.vanka@proton.me
description: "graphics programmer â€” demoscene, reverse engineering, 3D"
url: "https://aknavj.github.io"
baseurl: ""
github_username: aknavj

# build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "portfolio"

# exclude build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md
